---
title: "1.3 — The Ricardian View of Trade: Comparative Advantage — Practice Problems"
author: "ECON 324 — International Trade"
date: ""
output: pdf_document
---

*Gondor* and *Rohan* can each produce *oil (o)* and *linen (l)*. 

If Gondor devotes all of its resources to producing either good, it can produce 500 barrels of oil or 200 yards of linen. If Rohan devotes all of its resources to producing either good, it can produce 300 barrels of oil or 100 yards of linen. 

Currently, Gondor is producing 250 barrels of oil and 100 yards of linen, and Rohan is producing 150 barrels of oil and 50 units of linen.

Put oil (o) on the horizontal axis and linen (l) on the vertical axis.

1. Write the equation of each country's production possibilities frontier (PPF).

2. Graph each country's PPF. 

3. Which country has an *absolute* advantange in producing each good? Why?

4. Find each country's opportunity cost of producing each good.

5. Which country has a *comparative* advantage in producing each good? Why?

6. Which country should specialize in producing which good?

7. What will the range of possible terms of trade be? 