---
title: "Problem Set 2"
execute: 
  freeze: auto
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
```

::: {.callout-warning appearance="minimal"}
Due by 11:59 PM Thursday March 7 via by Blackboard Assignments
:::

Please read the [instructions](https://trades23.classes.ryansafner.com/assignments/problem-sets) for completing homeworks.

<p style="text-align:center;"><a class="btn btn-primary btn-lg" target="_blank" href="/files/assignment/02-problem-set-pdf.pdf"><i class="fas fa-file-pdf"></i> Download as PDF</a> <a class="btn btn-primary btn-lg" target="_blank" href="/files/assignment/02-problem-set-docx.docx"><i class="fa-regular fa-file-word"></i> Download as .docx</a></p>

## Answers

<p style="text-align:center"> <a target="_blank" href="/files/assignment/02-problem-set-answers.pdf"><span class="btn btn-primary btn-lg"><i class="fas fa-file-pdf"></i> Answers (PDF)</a> </p>

# Concepts and Critical Thinking

## Question 1

What are the sources of comparative advantage according to Hecksher-Ohlin theory, and what types of goods would we expect various countries to import and export?

## Question 2

According to Hecksher-Ohlin theory, what would we expect to happen to factor prices across countries that freely trade?

## Question 3

Explain the Leontief paradox.

## Question 4

How do specific factors and non-specific factors benefit or lose when trade increases? How do exports affect specific and non-specific factors' incomes? How do imports affect specific and non-specific factors' incomes?

## Question 5 

In perfect competition, firms set price equal to marginal cost. Why can't firms do this when there are internal economies of scale?

## Question 6

Respond to the following claim: “The world's poorest countries cannot find anything to export. There is no resource that is abundant--certainly not capital or land, and in small poor nations not even labor is abundant.”

## Question 7

Suppose a country can produce two goods, cloth (X) and food (Y). Explain what happens to the marginal rate of transformation & the PPF, and why, when all countries face (according to different models):

- Constant costs
- Increasing costs
- Decreasing costs

Drawing each example may help.

## Question 8

For each of the following parts, explain whether it is a case of *external* or *internal* economies of scale, and why.

### Part A

Most musical wind instruments in the United States are produced by more than a dozen factories in Elkhart, Indiana.

### Part B

All Hondas sold in the United States are either imported or produced in Marysville, Ohio.

### Part C

All airframes for Airbus, Europe’s only producer of large aircraft, are assembled in a factory in Toulouse, France.

### Part D

Hartford, Connecticut, is the insurance capital of the northeastern United States.


\clearpage

# Problems

## Question 9

Suppose in 2016, the United States imports $400 million in aircraft parts, and exports $500 million in aircraft parts. Calculate the Grubel-Lloyd Index and interpret what your results mean. 

## Question 10

Norway and Sweden have the same preferences, but have very different production opportunities. Norway has a long coast that borders on the north Atlantic, making it relatively more productive in fishing. Sweden has a relatively greater endowment of capital, making it relatively more productive in Volvos (automobiles). 

Graphically illustrate the gains from trade between the two countries using the H-O model, placing fish on the horizontal axis and Volvos on the vertical axis. Be sure to label the equilibria in autarky, specialization, equilibria after trade, the relative price lines, and imports and exports for each country. 