---
title: "Solving Systems of (Linear) Equations"
execute:
  freeze: auto
  echo: false
  warning: false
  message: false
---

```{r}
#| label: setup
library(tidyverse)
update_geom_defaults("label", list(family = "Fira Sans Condensed"))
update_geom_defaults("text", list(family = "Fira Sans Condensed"))

theme_guide <- theme_classic() + 
  theme(
    text = element_text(family = "Fira Sans Condensed", size = 18)
  )

```

To solve a system of simultaneous linear equations, there must be as many equations as there are variables:

\begin{align*}
12x+4y&=36 \\
6x-3y&=3 \\
\end{align*}

There are two methods we can use to solve this system:

## Substitution

First, we take one equation and solve for one of the variables. Here, we take the first, and solve for $x$: 

\begin{align*}
 		12x+4y&=36\\
 		12x&=36-4y\\
 		x&=3-\frac{1}{3}y\\
 		\end{align*}

Now we take this value and plug it into the other equation: 

\begin{align*}
 		6x-3y&=3\\
 		6(3-\frac{1}{3}y)-3y&=3\\
 	 		18-2y-3y&=3\\
 	 		18-5y&=3\\
 	 		-5y&=-15\\
 	 		y&=3\\
 		\end{align*}

Now that we know the value of one variable, plug it into either of the original equations to solve for the value of the other variable:

\begin{align*}
 		12x+4y&=36\\
 		12x+4(3)&=36\\
 		12x+12&=36\\
 		12x&=24\\
 		x&=2\\
 		\end{align*}

We should verify that our variables are correct, so plug $x$ and $y$ into each equation and make sure it is true. Let's start with the first equation:

\begin{align*}
 		12x+4y&=36\\
 		12(2)+4(3)&=36\\
 		24+12&=36 \checkmark \\
 		\end{align*}

We can do the same with the other equation:

\begin{align*}
 		6x-3y&=3\\
 		6(2)-3(3)&=3\\
 		12-9&=3 \checkmark \\
 		\end{align*}

## Elimination

We will multiply the equations by constants to make the coefficients of one variable equal. Here, let us try to make the coefficients in front of each equation's $x$ equal.

\begin{align*}
		[12x+4y&=36]*6\\
		[6x-3y&=3]*12\\
	\end{align*}

To do so, we will multiply the first equation by 6, and the second equation by 12. (We multiply each equation by the coefficient in front of the other equation's $x$ variable):  

\begin{align*}
		72x+24y&=216\\
		72x-36y&=36
	\end{align*}

Now we subtract the second equation from the first, which should get rid of $x$:

\begin{align*}
		72x+24y&=216\\
		-[72x-36y&=36]\\	
	\end{align*}

Be careful to distribute the minus sign carefully:

\begin{align*}
		[72x-72x]+[24y-(-36y)]&=[216-36]\\
		60y&=180\\
		y&=3\\
	\end{align*}

Now that we have the value of one variable, plug it in to either equation.

\begin{align*}
 		12x+4y&=36\\
 		12x+4(3)&=36\\
 		12x+12&=36\\
 		12x&=24\\
 		x&=2\\
 		\end{align*}
 
Now that we have both variables, we can plug them in to each equation to double check them, same as before.
